### ISSUE TITLE
Error in network.py

### ISSUE THREAD

**Issue by bblais** [Nico-Curti/NumPyNet#1]
I get an error running the MNIST example:

```
Traceback (most recent call last):
  File "MNIST.py", line 107, in <module>
    model.compile(optimizer=Adam(), metrics=[accuracy])
  File "/Users/bblais/opt/anaconda3/lib/python3.7/site-packages/NumPyNet-1.0.0-py3.7.egg/NumPyNet/network.py", line 287, in compile
    self._check_metrics(metrics)
  File "/Users/bblais/opt/anaconda3/lib/python3.7/site-packages/NumPyNet-1.0.0-py3.7.egg/NumPyNet/network.py", line 299, in _check_metrics
    if len(infos.args) - len(infos.defaults) != 2:
TypeError: object of type 'NoneType' has no len()
```

It's caused by the fact that infos.defaults is None (not zero) if there are no defaults, so there is no len().  a fix like,

```
     infos = inspect.getfullargspec(func)
      if infos.defaults:
        num_defaults=len(infos.defaults)
      else:
        num_defaults=0

      if len(infos.args) - num_defaults != 2:

```

solves the problem.

**Comment by Nico-Curti** [comment]
Thanks for reporting this. I added your fix in the network model ([L299](https://github.com/Nico-Curti/NumPyNet/blob/master/NumPyNet/network.py#L299)) + a test example for monitoring future changes ([test_network.py](https://github.com/Nico-Curti/NumPyNet/blob/master/testing/test_network.py#L24)).

The current NumPyNet version is still in development mode and any issue is more than welcome. I will temporarily close this issue (since it has been solved) but if you find any other problem in the code you can re-open this post or a new one and I will check ASAP.

Thanks
